[tool.poetry]
name = "ml-training"
version = "0.1.0"
description = ""
authors = ["Masato Naka <masatonaka1989@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.9"
tensorflow = "^2.16.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.3.7"


[tool.poetry.group.pytorch.dependencies]
torch = "1.13.1"
torchvision = "0.14.1"


[tool.poetry.group.ray.dependencies]
pyarrow = "14.0.1"
pandas = "2.1.1"
ray = {extras = ["train"], version = "^2.10.0"}


[tool.poetry.group.river.dependencies]
river = "0.15.0"
flask = "2.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
