# An unique identifier for the head node and workers of this cluster.
cluster_name: minimal

# Cloud-provider specific configuration.
provider:
    type: aws
    region: ap-northeast-1
    cache_stopped_nodes: False

docker:
    image: "rayproject/ray-ml:latest"
    container_name: "ray_container"

auth:
    ssh_user: ubuntu

available_node_types:
    ray.head.default:
        resources: {}
        node_config:
            InstanceType: m5.large
            ImageId: ami-088da9557aae42f39
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 100
    ray.worker.default:
        min_workers: 0
        max_workers: 2
        resources: {}
        node_config:
            InstanceType: m5.large
            ImageId: ami-088da9557aae42f39
            InstanceMarketOptions:
                MarketType: spot

setup_commands: []
initialization_commands:
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sudo sh get-docker.sh
    - sudo usermod -aG docker $USER
    - sudo systemctl restart docker -f
