name: actionlint

on:
  pull_request:

jobs:
  path-filter:
    outputs:
      lint: ${{steps.changes.outputs.lint}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@ebc4d7e9ebcb0b1eb21480bb8f43113e996ac77a # v3.0.1
        id: changes
        with:
          filters: |
            lint:
              - '.github/workflows/*'

  status-check:
    # This job is used for the branch's branch protection rule's status check.
    # If all dependent jobs succeed or are skipped this job succeeds.
    runs-on: ubuntu-latest
    needs:
      - actionlint
    permissions: {}
    if: failure()
    steps:
      - run: exit 1

  actionlint:
    if: needs.path-filter.outputs.lint == 'true'
    needs: path-filter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
