name: lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & Poetry
        uses: ./.github/actions/setup-poetry

      - name: ruff
        run: poetry run ruff check
