name: python
on:
  pull_request:
    paths:
      - poetry.lock
      - pyproject.toml
      - 'pytorch/**'
      - '!pytorch/README.md'
      - '!pytorch/**/README.md'
      - .github/workflows/python.yml

jobs:
  path-filter:
    outputs:
      pytorch: ${{steps.changes.outputs.pytorch}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@ebc4d7e9ebcb0b1eb21480bb8f43113e996ac77a # v3.0.1
        id: changes
        with:
          filters: |
            pytorch:
              - poetry.lock
              - pyproject.toml
              - 'pytorch/**'
              - '!pytorch/README.md'
              - '!pytorch/**/README.md'
              - .github/workflows/python.yml

  status-check:
    # This job is used for the branch's branch protection rule's status check.
    # If all dependent jobs succeed or are skipped this job succeeds.
    runs-on: ubuntu-latest
    needs:
      - pytorch
    permissions: {}
    if: failure()
    steps:
      - run: exit 1

  pytorch:
    if: needs.path-filter.outputs.pytorch == 'true'
    needs: path-filter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & Poetry
        uses: ./.github/actions/setup-poetry

      - name: run
        working-directory: pytorch
        run: |
          poetry run python distributed_example.py
