name: pytorch
on:
  pull_request:
    paths:
      - 'pytorch/**'
      - '!pytorch/README.md'
      - '!pytorch/**/README.md'
      - .github/workflows/pytorch.yml
defaults:
  run:
    working-directory: pytorch
jobs:
  pytorch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & Poetry
        uses: ./.github/actions/setup-poetry

      - name: run
        run: |
          poetry run python distributed_example.py
