name: pytorch
on:
  pull_request:
    paths:
      - 'pytorch/**'
      - '!pytorch/README.md'
      - '!pytorch/**/README.md'
      - .github/workflows/pytorch.yml
defaults:
  run:
    working-directory: pytorch
jobs:
  pytorch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
      - name: install
        run: pip install -r requirements.txt
      - name: run
        run: |
          python distributed_example.py
