name: ray
on:
  pull_request:
    paths:
      - 'ray/**'
      - '!ray/README.md'
      - '!ray/**/README.md'
      - .github/workflows/ray.yml
defaults:
  run:
    working-directory: ray
jobs:
  ray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & Poetry
        uses: ./.github/actions/setup-poetry

      - name: 02-task-pattern
        run: poetry run python 02-task-pattern/task_pattern_map_and_reduce.py

      # - name: 05-train simple with torch
      #   run: python 05-train/simple_example.py -b torch

      # - name: 05-train simple with tensorflow
      #   run: python 05-train/simple_example.py -b tensorflow

      # == Status ==
      # Current time: 2023-09-23 10:32:09 (running for 00:07:35.39)
      # Memory usage on this node: 1.6/6.8 GiB
      # Using FIFO scheduling algorithm.
      # Resources requested: 0/2 CPUs, 0/0 GPUs, 0.0/3.48 GiB heap, 0.0/1.74 GiB objects
      # Result logdir: /home/runner/ray_results/TensorflowTrainer_2023-09-23_10-24-33
      # Number of trials: 1/1 (1 PENDING)
      # +-------------------------------+----------+-------+
      # | Trial name                    | status   | loc   |
      # |-------------------------------+----------+-------|
      # | TensorflowTrainer_6383c_00000 | PENDING  |       |
      # +-------------------------------+----------+-------+

      # - name: 05-train tensorflow example
      #   run: python 05-train/tensorflow_example.py --smoke-test
      # TODO: https://github.com/nakamasato/ml-training/issues/298
