name: ray
on:
  pull_request:
    paths:
      - 'ray/**'
      - '!ray/README.md'
      - '!ray/**/README.md'
      - .github/workflows/ray.yml
defaults:
  run:
    working-directory: ray
jobs:
  ray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
      - name: install
        run: pip install -r requirements.txt
      - name: run
        run: |
          python 02-task-pattern/task_pattern_map_and_reduce.py
          python 05-train/simple_example.py -b torch
          python 05-train/simple_example.py -b tensorflow
          python 05-train/tensorflow_example.py --smoke-test
