name: river
on:
  pull_request:
    paths:
      - 'river/**'
      - '!river/README.md'
      - '!river/**/README.md'
      - .github/workflows/river.yml

jobs:
  check:
    strategy:
      matrix:
        execute:
          - dir: river/quickstart
            script: main.py
          - dir: river/examples/fm-for-datalens
            script: main.py --native-prediction --linear-regression --funk-mf --biased-mf --mimic-biased-mf --mf-with-improved-feature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
      - name: install
        working-directory: ${{ matrix.execute.dir }}
        run: pip install -r requirements.txt
      - name: run
        working-directory: ${{ matrix.execute.dir }}
        run: python ${{ matrix.execute.script }}
