name: river
on:
  pull_request:
    paths:
      - 'river/**'
      - '!river/README.md'
      - '!river/**/README.md'
      - .github/workflows/river.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & Poetry
        uses: ./.github/actions/setup-poetry

      - name: run river/quickstart/main.py
        run: poetry run python river/quickstart/main.py

      - name: run river/examples/fm-for-datalens/main.py
        run: poetry run python river/examples/fm-for-datalens/main.py --native-prediction --linear-regression --funk-mf --biased-mf --mimic-biased-mf --mf-with-improved-feature
