name: tensorflow
on:
  pull_request:
    paths:
      - poetry.lock
      - pyproject.toml
      - 'tensorflow/**'
      - '!tensorflow/README.md'
      - '!tensorflow/**/README.md'
      - .github/workflows/tensorflow.yml

jobs:
  tensorflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & Poetry
        uses: ./.github/actions/setup-poetry

      - name: run
        run: |
          poetry run python tensorflow/parameter-server-training/train_in_process_cluster.py
